### PR TITLE
Set `req.originalUrl` before running middleware

### PR DESCRIPTION
**Pull request by nwoltman**
For better compatibility with Express middleware.

### CODE REVIEW

**Comment by nwoltman** [comment]
> it will alter the shape of the `req` object on the fly, slowing things down

I agree that this would impact performance. Unfortunately a lot of Express middleware alter the shape of the `req` object anyway, so it might not make a difference.

> Is `originalUrl` used in `Express` anywhere? Why does this improves compatibility?

The main middleware I'm using in production is [`serve-static`](https://github.com/expressjs/serve-static), and the first thing it does is parse the URL using [`parseurl`](https://github.com/pillarjs/parseurl) which [adds extra properties to `req`](https://github.com/pillarjs/parseurl/blob/master/index.js#L54) and [tries to use `req.originalUrl`](https://github.com/pillarjs/parseurl/blob/master/index.js#L66).

I don't have any bugs from this because I set `serve-static`'s [`index`](https://github.com/expressjs/serve-static#index) and [`redirect`](https://github.com/expressjs/serve-static#redirect) options to `false`, but someone who uses the default values would get this bug:

```js
fastify.use('/static', serveStatic('./static'));
```

```
/static
   |___ index.html
   |___ /blog
          |___ index.html
```

Going to `http://localhost/static/blog` should make `serve-static` redirect the request to `http://localhost/static/blog/`, but since the middleware was prefixed with `/static` and there is no `req.originalUrl`, it uses `req.url` (which is `'/blog'`) so it will redirect to `http://localhost/blog/` instead.

Where I am affected is in development where I use Express's [`morgan` middleware](https://github.com/expressjs/morgan) to log requests. Requests made to middleware with a prefix (like the `serve-static` example above) will have the prefix stripped, so it will log the URL as `/blog` instead of `/static/blog`.

**Comment by jsumners** [comment]
A couple of things:

1. https://www.npmjs.com/package/fastify-static
2. Fastify includes a logger. Simply `const fastify = require('fastify')({logger: true})` to get `req.log.{info,debug,etc}` in your handlers.

**Comment by nwoltman** [comment]
1. That's awesome! I didn't know about `fastify-static`. It should be added to the [Ecosystem docs](https://github.com/fastify/fastify/blob/master/docs/Ecosystem.md#core).
2. I just like `morgan`'s logging format for logging requests in development. It's one simple line for each request with a colored status code. I still use a `pino` logger for logging other things.

**Comment by jsumners** [comment]
Odd, I thought `fastify-static` was in the list. Care to fix that via a PR?

**Comment by nwoltman** [comment]
Sure. PR is fastify/fastify#55

**Comment by mcollina** [comment]
@nwoltman can you send a PR setting `req.originalUrl` in https://github.com/fastify/fastify/blob/master/fastify.js#L156

**Pull request merged**
