### PR TITLE
Should match all chain

### PR DESCRIPTION
**Pull request by allevo**
This PR aims to enlight the issue described at https://github.com/fastify/fastify/pull/295

The prefix `/` generates the regex `/^\/(?:\/(?=$))?(?=\/|$)/i`. The end of this regex `(?=\/|$)` doesn't match.

But I'm a regex expert

### CODE REVIEW

**Comment by mcollina** [comment]
Would you like also to attempt a fix?

**Comment by allevo** [comment]
@mcollina yes but are we agree that this test should pass?
And maybe this could be a `path-to-regex`  issue or a middie missconfiguration

**Comment by mcollina** [comment]
I think the root, null and undefined are bugs, while the others are not bugs

**Comment by allevo** [comment]
Why should `/inner/` not match `/inner/path`?

Anyway this could be a `path-to-regex` miss feature https://github.com/pillarjs/path-to-regexp/issues/123 ?

**Comment by mcollina** [comment]
Our goal is to support express middlewares. path-to-regexp is what express uses, so we have the same behavior.

**Comment by allevo** [comment]
Actually:
```js
'use strict'

const app = require('express')()

app.use('/', function(req, res, next) {
  console.log('/')
  next()
})
app.use('/a', function(req, res, next) {
  console.log('/a')
  next()
})
app.use('/a/', function(req, res, next) {
  console.log('/a/')
  next()
})
app.use('/a/b', function(req, res, next) {
  console.log('/a/b')
  next()
})

app.listen(3000)
```

Calling `http://localhost:3000/a/b` the above code prints:
```
/
/a
/a/
/a/b
```

If we want to be compliant to express we need to use the same `path-to-regex` version: we use [2.0.0](https://github.com/fastify/middie/blob/master/package.json#L46); `express` uses [0.1.7](https://github.com/expressjs/express/blob/4.x/package.json#L47)

**Comment by mcollina** [comment]
We might as well do that, even if it makes me uncomfortable.

**Comment by allevo** [comment]
I've downgraded the `path-to-regex` package version to "1.7.0".
Now all the tests should pass.

NB: check if you like the assertion

**Comment by mcollina** [comment]
I would really like this to follow path-to-regexp 2 (see https://github.com/pillarjs/path-to-regexp/pull/114#issue-251808326).

Moreover, I would like this to match find-my-way if possible.
@delvedor can you please check?

**Comment by allevo** [comment]
Yeah but the v2 version the slashed middlewares are not matched.
Is this ok?

As a developer if I set a middleware at `/inner/`, I expect the path `/inner/path` matches it.

Anyway please tell me which behaviour you like

**Comment by mcollina** [comment]
It's ok to go back to 1.7. Ideally this would be addressed in a future release: can you please drop a note on https://github.com/pillarjs/path-to-regexp/issues/123 with an example of what got broken?

**Comment by mcollina** [comment]
IMHO we should use the latest one and normalize by adding (or removing) a slash here.

**Pull request merged**
